force-app/main/default/objects/GanttResource__c/GanttResource__c.object-meta.xml
<CustomObject>
    <label>GanttResource</label>
    <nameField>
        <label>GanttResource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GanttResources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GanttResourceAssignment__c/GanttResourceAssignment__c.object-meta.xml
<CustomObject>
    <label>GanttResourceAssignment</label>
    <nameField>
        <displayFormat>GRA{0000000000}</displayFormat>
        <label>GanttResourceAssignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GanttResourceAssignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GanttResourceAssignment__c/fields/Delay__c.field-meta.xml
<CustomField>
    <fullName>Delay__c</fullName>
    <label>Delay</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GanttResourceAssignment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GanttResourceAssignment__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>fixedDates</fullName>
            </value>
            <value>
                <fullName>fixedDuration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GanttResourceAssignment__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>GanttResource__c</referenceTo>
    <relationshipLabel>GanttResourceAssignments</relationshipLabel>
    <relationshipName>GanttResourceAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GanttResourceAssignment__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <label>Task</label>
    <referenceTo>GanttTask__c</referenceTo>
    <relationshipLabel>GanttResourceAssignments</relationshipLabel>
    <relationshipName>GanttResourceAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GanttResourceAssignment__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GanttData.cls
/**
 * Created 23.01.2020.
 */

public with sharing class GanttData {

    @RemoteAction
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getTasks() {
        
        // fetching the Records via SOQL
        List<GanttTask__c> Tasks = new List<GanttTask__c>();
        Tasks = [SELECT Id, Name, Start_Date__c, Duration__c, Parent__c FROM GanttTask__c];

        List<GanttLink__c> Links = new List<GanttLink__c>();
        Links = [SELECT Id, Type__c, Source__c, Target__c FROM GanttLink__c];

        List<GanttResource__c> Resources = new List<GanttResource__c>();
        Resources = [SELECT Id, Name FROM GanttResource__c];

        List<GanttResourceAssignment__c> Assignments = new List<GanttResourceAssignment__c>();
        Assignments = [SELECT Id, Task__c, Resource__c, Mode__c, Value__c, Delay__c, Duration__c, Start_Date__c, End_Date__c FROM GanttResourceAssignment__c];

        Map<String, Object> result = new Map<String, Object>{'tasks' => Tasks, 'links' => Links, 'resources' => Resources, 'assignments' => Assignments };
        return result;
   }
}